/* ═══ FIELD WIDTHS ═══ */
const W_AL=2, W_FN=4, W_DS=14, W_TM=5, W_GT=4, W_ST=9;
const WTOT=W_AL+W_FN+W_DS+W_TM+W_GT+W_ST;

/* Field boundaries for random flip targeting */
const FIELDS=[
  {s:0, e:W_AL},
  {s:W_AL, e:W_AL+W_FN},
  {s:W_AL+W_FN, e:W_AL+W_FN+W_DS},
  {s:W_AL+W_FN+W_DS, e:W_AL+W_FN+W_DS+W_TM},
  {s:W_AL+W_FN+W_DS+W_TM, e:W_AL+W_FN+W_DS+W_TM+W_GT},
  {s:W_AL+W_FN+W_DS+W_TM+W_GT, e:WTOT}
];

/* ═══ DESTINATIONS ═══ */
const DS=[
['NEW YORK JFK','JFK'],['LOS ANGELES','LAX'],['CHICAGO OHARE','ORD'],
['SAN FRANCISCO','SFO'],['MIAMI','MIA'],['TORONTO','YYZ'],
['MEXICO CITY','MEX'],['SAO PAULO','GRU'],['BUENOS AIRES','EZE'],
['LONDON','LHR'],['PARIS CDG','CDG'],['FRANKFURT','FRA'],
['AMSTERDAM','AMS'],['MADRID','MAD'],['ROMA','FCO'],
['ZUERICH','ZRH'],['ISTANBUL','IST'],['MUENCHEN','MUC'],
['DUBAI','DXB'],['DOHA','DOH'],['TOKYO NARITA','NRT'],
['TOKYO HANEDA','HND'],['HONG KONG','HKG'],['SINGAPORE','SIN'],
['SEOUL INCHEON','ICN'],['BANGKOK','BKK'],['TAIPEI','TPE'],
['SHANGHAI','PVG'],['BEIJING','PEK'],['DELHI','DEL'],
['MUMBAI','BOM'],['KUALA LUMPUR','KUL'],['SYDNEY','SYD'],
['AUCKLAND','AKL'],['JOHANNESBURG','JNB'],['NAIROBI','NBO'],
['DUBLIN','DUB'],['COPENHAGEN','CPH'],['OSLO','OSL'],['JAKARTA','CGK'],
['WARSAW','WAW'],['BUDAPEST','BUD'],['PRAGUE','PRG'],['MANCHESTER','MAN'],
['BASEL','BSL'],['IZMIR','ADB'],['CAIRO','CAI'],['POZNAN','POZ'],
['NEWARK','EWR'],['ATLANTA','ATL'],['DALLAS FTW','DFW'],['HOUSTON','IAH'],
['SEATTLE','SEA'],['DENVER','DEN'],['BOSTON','BOS'],['CANCUN','CUN'],
['BOGOTA','BOG'],['SANTIAGO','SCL'],['LIMA','LIM'],['LISBON','LIS'],
['BARCELONA','BCN'],['VIENNA','VIE'],['BRUSSELS','BRU'],['ATHENS','ATH'],
['STOCKHOLM','ARN'],['HELSINKI','HEL'],['EDINBURGH','EDI'],
['ABU DHABI','AUH'],['JEDDAH','JED'],['CASABLANCA','CMN'],
['ADDIS ABABA','ADD'],['LAGOS','LOS'],['GUANGZHOU','CAN'],
['OSAKA KANSAI','KIX'],['MANILA','MNL'],['HO CHI MINH','SGN'],
['MELBOURNE','MEL'],['PERTH','PER'],['KOLKATA','CCU'],['SAPPORO','CTS'],
['WASHINGTON','IAD'],['PHILADELPHIA','PHL'],['MINNEAPOLIS','MSP'],
['DETROIT','DTW'],['CHARLOTTE','CLT'],['PHOENIX','PHX'],
['ORLANDO','MCO'],['SAN DIEGO','SAN'],['PORTLAND','PDX'],
['VANCOUVER','YVR'],['MONTREAL','YUL'],['HAVANA','HAV'],
['PANAMA CITY','PTY'],['RIO DE JANEIRO','GIG'],['BRASILIA','BSB'],
['MILAN','MXP'],['BERLIN','BER'],['HAMBURG','HAM'],
['DUESSELDORF','DUS'],['GENEVE','GVA'],['NICE','NCE'],
['BUCHAREST','OTP'],['TEL AVIV','TLV'],['MUSCAT','MCT'],
['BAHRAIN','BAH'],['RIYADH','RUH'],['KUWAIT','KWI'],
['CHENNAI','MAA'],['BANGALORE','BLR'],['HANOI','HAN'],
['CHENGDU','CTU'],['SHENZHEN','SZX'],['COLOMBO','CMB'],
['MALE','MLE'],['PHUKET','HKT'],['BALI','DPS'],
];

/* ═══ AIRPORTS — 76 worldwide ═══ */
function $A(c,n,al,gp,sd,s){return{c,n,s:s||'DEPARTURES',al:al.split(' '),gp:gp.split(' '),sd}}
const AP=[
/* ── EUROPE ── */
$A('FRA','FRANKFURT AM MAIN','LH UA SQ NH CX TK EK AF BA DL MS XQ LO AI AC SA','A B C Z',1,'ABFLUG · DEPARTURES'),
$A('LHR','LONDON HEATHROW','BA VS AA UA EK SQ NH LH AF QF DL TK CX AI','A B C',2),
$A('AMS','AMSTERDAM SCHIPHOL','KL AF LH BA TK EK DL SQ CX UA NH','B C D E F',3,'VERTREK · DEPARTURES'),
$A('CDG','PARIS CHARLES DE GAULLE','AF BA LH DL AA EK SQ CX NH TK UA','K L M',4,'DEPARTS · DEPARTURES'),
$A('FCO','ROMA FIUMICINO','AZ BA LH AF EK TK UA DL SQ QR','D E F G',5,'PARTENZE · DEPARTURES'),
$A('IST','ISTANBUL HAVALIMANI','TK LH BA AF EK QR SQ UA DL KL','A D E F',6,'KALKIŞLAR · DEPARTURES'),
$A('MUC','MUENCHEN F.J. STRAUSS','LH UA TK EK SQ BA AF NH CX DL','G H K',7,'ABFLUG · DEPARTURES'),
$A('ZRH','ZUERICH KLOTEN','LX LH BA EK SQ TK UA AF NH','A B D E',8,'ABFLUG · DEPARTURES'),
$A('MAD','MADRID BARAJAS','IB BA LH AF AA EK TK UA DL SQ','H J K S',9,'SALIDAS · DEPARTURES'),
$A('BCN','BARCELONA EL PRAT','VY IB BA LH AF EK TK UA','A B C D',35,'SALIDAS · DEPARTURES'),
$A('LIS','LISBON PORTELA','TP BA LH AF EK TK SQ UA','1 2',36,'PARTIDAS · DEPARTURES'),
$A('VIE','VIENNA SCHWECHAT','OS LH BA TK EK SQ UA AF','D F G',37,'ABFLUG · DEPARTURES'),
$A('BRU','BRUSSELS ZAVENTEM','SN LH BA AF TK EK UA DL','A B',38,'VERTREK · DEPARTURES'),
$A('CPH','COPENHAGEN KASTRUP','SK LH BA AF TK EK SQ UA NH','A B C',39,'AFGANGE · DEPARTURES'),
$A('OSL','OSLO GARDERMOEN','SK LH BA AF TK EK DL UA','D E F',40,'AVGANGER · DEPARTURES'),
$A('ARN','STOCKHOLM ARLANDA','SK LH BA AF TK EK SQ UA','2 5',41,'AVGÅNGAR · DEPARTURES'),
$A('HEL','HELSINKI VANTAA','AY LH BA AF TK EK SQ NH','2',42,'LÄHDÖT · DEPARTURES'),
$A('DUB','DUBLIN','EI BA LH AF TK EK AA UA DL','1 2',43),
$A('MAN','MANCHESTER','BA TK EK SQ','1 2 3',44),
$A('EDI','EDINBURGH','BA TK EK','G H',45),
$A('WAW','WARSAW CHOPIN','LO LH BA AF TK EK UA SQ','A B',46,'ODLOTY · DEPARTURES'),
$A('PRG','PRAGUE VACLAV HAVEL','OK LH BA AF TK EK SQ UA','1 2 C D',47,'ODLETY · DEPARTURES'),
$A('BUD','BUDAPEST LISZT FERENC','W6 TK EK','A B',48,'INDULÁS · DEPARTURES'),
$A('ATH','ATHENS ELEFTHERIOS','A3 LH BA AF TK EK SQ UA','A B',49,'ΑΝΑΧΩΡΗΣΕΙΣ · DEPARTURES'),
/* ── MIDDLE EAST ── */
$A('DXB','DUBAI INTERNATIONAL','EK FZ QR BA LH SQ CX QF AF TK NH','A B C D',10,'DEPARTURES'),
$A('DOH','HAMAD INTERNATIONAL','QR BA LH EK TK SQ CX AF NH UA','A B C D',11,'DEPARTURES'),
$A('AUH','ABU DHABI INTL','EY BA AF TK SQ','A B C',50,'DEPARTURES'),
$A('JED','JEDDAH K.A.AZIZ','SV EK QR TK BA','N S',51,'DEPARTURES'),
/* ── AFRICA ── */
$A('CAI','CAIRO INTERNATIONAL','MS EK QR TK BA LH AF','1 2 3',52),
$A('NBO','NAIROBI JKIA','KQ EK QR TK BA ET','1 2',53),
$A('JNB','JOHANNESBURG O.R. TAMBO','SA EK QR BA LH AF TK SQ','A B',54),
$A('CMN','CASABLANCA MOHAMMED V','AT EK QR TK AF BA','1 2',55),
$A('ADD','ADDIS ABABA BOLE','ET EK TK QR','1 2',56),
$A('LOS','LAGOS MURTALA MUHAMMED','W3 EK QR TK BA ET','D E',57),
/* ── ASIA ── */
$A('HND','TOKYO HANEDA','NH JL AA DL UA BA LH AF SQ CX TK EK QF','',12),
$A('NRT','TOKYO NARITA','JL NH AA DL UA BA LH AF SQ CX TK EK','1 2 3',13),
$A('PEK','BEIJING CAPITAL','CA CZ MU NH JL BA LH AF EK SQ TK UA DL','D E T',14),
$A('PVG','SHANGHAI PUDONG','MU CA CZ NH JL BA LH AF EK SQ TK','1 2',58),
$A('CAN','GUANGZHOU BAIYUN','CZ CA MU SQ TK EK BA NH JL','A B',59),
$A('HKG','HONG KONG INTL','CX HX BA SQ NH JL QF EK TK LH UA AA','',15),
$A('ICN','SEOUL INCHEON','KE OZ NH JL CX SQ UA DL AA LH TK EK','A B C',16),
$A('SIN','SINGAPORE CHANGI','SQ BA QF NH JL CX EK LH AF UA TK KE','A B C D',17),
$A('BKK','BANGKOK SUVARNABHUMI','TG SQ CX NH JL EK BA LH QR KE QF','C D E F G',18),
$A('DEL','INDIRA GANDHI INTL','AI UK SQ EK BA LH TK QR NH AF UA','T3',19,'DEPARTURES'),
$A('KUL','KUALA LUMPUR INTL','MH AK SQ CX EK BA LH TK QR','C J',60),
$A('CGK','JAKARTA SOEKARNO-HATTA','GA SQ CX EK BA LH TK QR NH','D E F',61),
$A('MNL','MANILA NINOY AQUINO','PR SQ CX EK BA NH JL KE','1 3',62),
$A('TPE','TAIWAN TAOYUAN','CI BR NH JL SQ CX EK BA LH UA','A B D',63),
$A('KIX','OSAKA KANSAI','JL NH SQ CX KE OZ EK TK BA LH','1 2',64),
$A('CTS','SAPPORO NEW CHITOSE','NH JL','',65),
$A('SGN','HO CHI MINH TAN SON NHAT','VN SQ CX EK BA TK QR NH JL KE','1 2',66),
$A('CCU','KOLKATA NETAJI SUBHAS','AI SQ EK','T1 T2',67),
/* ── AMERICAS ── */
$A('JFK','NEW YORK J.F. KENNEDY','AA DL UA JL BA EK SQ LH AF CX TK QR NH','A B C',20),
$A('EWR','NEWARK LIBERTY INTL','UA DL AA JL BA EK SQ LH AF TK NH','A B C',21),
$A('LAX','LOS ANGELES INTL','UA AA DL SQ CX QF NH JL BA EK LH AF TK','B T',22),
$A('ORD','CHICAGO O\'HARE','UA AA DL BA LH NH JL TK EK AF SQ','B C H K',23),
$A('ATL','ATLANTA HARTSFIELD','DL AA UA BA LH AF TK EK SQ','A B C D E F',68),
$A('SFO','SAN FRANCISCO INTL','UA AA DL SQ CX NH JL BA EK LH','A G',69),
$A('MIA','MIAMI INTERNATIONAL','AA DL UA BA LH AF IB EK TK','D E F G H J',70),
$A('DFW','DALLAS FORT WORTH','AA DL UA BA QR EK','A B C D E',71),
$A('IAH','HOUSTON G. BUSH','UA DL AA BA LH EK TK','A B C D E',72),
$A('SEA','SEATTLE-TACOMA','DL UA AA NH SQ','A B C D N S',73),
$A('DEN','DENVER INTERNATIONAL','UA DL AA LH','A B C',74),
$A('BOS','BOSTON LOGAN','DL UA AA JL BA EK LH AF TK','A B C E',75),
$A('YYZ','TORONTO PEARSON','AC WS AA UA DL BA LH AF TK EK NH SQ','D E F',24,'DEPARTURES · DEPARTS'),
$A('MEX','MEXICO CITY INTL','AM UA AA DL BA LH AF IB TK','1 2',25,'SALIDAS · DEPARTURES'),
$A('GRU','SAO PAULO GUARULHOS','LA G3 AA DL UA AF BA LH EK TK IB','D E',26,'PARTIDAS · DEPARTURES'),
$A('EZE','BUENOS AIRES EZEIZA','AR LA AA DL UA BA AF IB EK','A B C',76),
$A('BOG','BOGOTA EL DORADO','AV LA AA DL UA AF IB TK','1',77),
$A('SCL','SANTIAGO A.M. BENITEZ','LA AA AF IB','',78,'SALIDAS · DEPARTURES'),
$A('LIM','LIMA JORGE CHAVEZ','LA AV AA DL UA IB','',79),
$A('CUN','CANCUN INTERNATIONAL','AM UA AA DL BA','1 2 3 4',80),
/* ── OCEANIA ── */
$A('SYD','SYDNEY KINGSFORD SMITH','QF VA SQ EK CX NH BA UA AA DL LH NZ','A B C',27),
$A('MEL','MELBOURNE TULLAMARINE','QF VA SQ EK CX UA','1 2',81),
$A('AKL','AUCKLAND','NZ QF VA SQ EK','',82),
$A('PER','PERTH','QF VA SQ EK','1 2',83),
/* ── EUROPE EXPANDED ── */
$A('BER','BERLIN BRANDENBURG','LH EW TK EK SQ BA AF','1 2',84,'ABFLUG · DEPARTURES'),
$A('HAM','HAMBURG','LH EW TK BA AF','1 2',85,'ABFLUG · DEPARTURES'),
$A('DUS','DUESSELDORF','LH EW TK EK BA','A B C',86,'ABFLUG · DEPARTURES'),
$A('MXP','MILANO MALPENSA','AZ LH BA AF EK TK','1 2',87,'PARTENZE · DEPARTURES'),
$A('GVA','GENEVE COINTRIN','LX LH BA AF EK','1 2',88),
$A('NCE','NICE COTE D AZUR','AF BA LH EK TK','1 2',89,'DEPARTS · DEPARTURES'),
$A('OTP','BUCHAREST OTOPENI','RO TK LH BA AF','',90),
$A('TLV','TEL AVIV BEN GURION','LY EL TK LH BA AF EK','3',91),
$A('BGY','BERGAMO ORIO AL SERIO','FR W6','1',92,'PARTENZE · DEPARTURES'),
$A('SVO','MOSCOW SHEREMETYEVO','SU LH TK AF','B C D E',93),
$A('LED','ST PETERSBURG PULKOVO','SU TK','1',94),
$A('KBP','KYIV BORYSPIL','PS TK LH BA','D F',95),
$A('OPO','PORTO','TP FR LH BA','1',96,'PARTIDAS · DEPARTURES'),
$A('PMI','PALMA DE MALLORCA','IB VY FR BA LH','A',97,'SALIDAS · DEPARTURES'),
$A('AGP','MALAGA COSTA DEL SOL','IB VY FR BA LH','3',98,'SALIDAS · DEPARTURES'),
$A('ALC','ALICANTE ELCHE','IB VY FR BA','1',99,'SALIDAS · DEPARTURES'),
$A('TFS','TENERIFE SUR','IB VY FR BA LH','',100,'SALIDAS · DEPARTURES'),
$A('LTN','LONDON LUTON','W6 FR EZY','1',101),
$A('STN','LONDON STANSTED','FR BA','1',102),
$A('LGW','LONDON GATWICK','BA EZY VS DL AA','N S',103),
$A('GLA','GLASGOW','BA LH FR','1',104),
$A('BHX','BIRMINGHAM','BA TK FR','1',105),
$A('LYS','LYON SAINT EXUPERY','AF LH TK EK','1 2',106,'DEPARTS · DEPARTURES'),
$A('TLS','TOULOUSE BLAGNAC','AF BA LH','A B',107,'DEPARTS · DEPARTURES'),
$A('MRS','MARSEILLE PROVENCE','AF LH BA TK','1 2',108,'DEPARTS · DEPARTURES'),
$A('SOF','SOFIA','FB TK LH W6','1 2',109),
$A('ZAG','ZAGREB','OU TK LH','',110),
$A('BEG','BELGRADE NIKOLA TESLA','JU TK LH W6','1 2',111),
$A('RIX','RIGA','BT LH TK FR','',112),
$A('VNO','VILNIUS','W6 FR LH TK','',113),
$A('TLL','TALLINN','BT LH TK FR','',114),
$A('KEF','REYKJAVIK KEFLAVIK','FI BA DL UA','',115),
/* ── MIDDLE EAST EXPANDED ── */
$A('RUH','RIYADH KING KHALID','SV EK QR TK LH BA','1 2 5',116,'DEPARTURES'),
$A('MCT','MUSCAT','WY EK QR TK BA','1',117),
$A('BAH','BAHRAIN','GF EK QR TK BA','',118),
$A('KWI','KUWAIT','KU EK QR TK BA','1 4',119,'DEPARTURES'),
$A('AMM','AMMAN QUEEN ALIA','RJ EK TK LH BA','',120),
$A('BEY','BEIRUT R. HARIRI','ME TK LH AF BA','',121),
/* ── AFRICA EXPANDED ── */
$A('CPT','CAPE TOWN','SA EK QR TK BA','1 2',122),
$A('DUR','DURBAN KING SHAKA','SA EK','1 2',123),
$A('DAR','DAR ES SALAAM','ET EK QR TK KQ','1 2 3',124),
$A('EBB','ENTEBBE','ET EK QR TK KQ','',125),
$A('ACC','ACCRA KOTOKA','ET EK TK BA','3',126),
$A('ALG','ALGIERS H. BOUMEDIENE','AH AF TK','1 2 3',127),
$A('TUN','TUNIS CARTHAGE','TU AF TK LH','1 2',128),
$A('MRU','MAURITIUS SSR','MK EK BA AF','',129),
/* ── ASIA EXPANDED ── */
$A('BOM','MUMBAI CHHATRAPATI','AI EK SQ BA LH TK QR','1 2',130,'DEPARTURES'),
$A('BLR','BANGALORE KEMPEGOWDA','AI SQ EK BA LH TK','1 2',131),
$A('MAA','CHENNAI','AI SQ EK BA LH','1 3',132),
$A('HYD','HYDERABAD RAJIV GANDHI','AI SQ EK BA','',133),
$A('CMB','COLOMBO BANDARANAIKE','UL SQ EK QR','',134),
$A('DAC','DHAKA SHAHJALAL','BG SQ EK TK','1 2',135),
$A('KTM','KATHMANDU TRIBHUVAN','RA TK QR','',136),
$A('RGN','YANGON','UB SQ TK QR','',137),
$A('HAN','HANOI NOI BAI','VN SQ CX TK QR','1 2',138),
$A('DPS','BALI NGURAH RAI','GA SQ CX EK QR','D I',139),
$A('HKT','PHUKET','TG SQ CX EK','D I',140),
$A('MLE','MALE VELANA','UL SQ EK QR','',141),
$A('CTU','CHENGDU TIANFU','CA CZ MU SQ','1 2',142),
$A('SZX','SHENZHEN BAOAN','CZ CA MU SQ','A B',143),
$A('XIY','XIAN XIANYANG','CA CZ MU','1 2 3',144),
$A('NKG','NANJING LUKOU','CA CZ MU','1 2',145),
$A('WUH','WUHAN TIANHE','CA CZ MU','1 2 3',146),
$A('CKG','CHONGQING JIANGBEI','CA CZ MU','1 2 3',147),
$A('FUK','FUKUOKA','NH JL','D I',148),
$A('NGO','NAGOYA CHUBU','NH JL','1 2',149),
/* ── AMERICAS EXPANDED ── */
$A('YVR','VANCOUVER','AC WS AA DL UA BA CX NH','D E',150),
$A('YUL','MONTREAL P.E. TRUDEAU','AC WS AA DL UA AF LH TK','',151,'DEPARTS · DEPARTURES'),
$A('MSP','MINNEAPOLIS ST PAUL','DL UA AA SQ','C D E F G',152),
$A('DTW','DETROIT METRO WAYNE','DL AA UA LH','A B',153),
$A('PHL','PHILADELPHIA','AA DL UA BA LH','A B C D E F',154),
$A('CLT','CHARLOTTE DOUGLAS','AA DL UA LH BA','A B C D E',155),
$A('PHX','PHOENIX SKY HARBOR','AA DL UA WN','A B C D',156),
$A('MCO','ORLANDO','DL AA UA BA','A B',157),
$A('SAN','SAN DIEGO','AA DL UA WN','1 2',158),
$A('PDX','PORTLAND','DL AA UA AS','C D E',159),
$A('BWI','BALTIMORE WASHINGTON','WN AA DL UA BA','A B C D E',160),
$A('DCA','WASHINGTON REAGAN','AA DL UA','A B C',161),
$A('IAD','WASHINGTON DULLES','UA AA DL LH TK EK','A B C D',162),
$A('TPA','TAMPA','AA DL UA WN BA','A B C E F',163),
$A('BNA','NASHVILLE','WN DL AA UA','A B C D',164),
$A('AUS','AUSTIN BERGSTROM','AA DL UA WN BA','',165),
$A('RDU','RALEIGH DURHAM','AA DL UA','1 2',166),
$A('SLC','SALT LAKE CITY','DL AA UA','A B',167),
$A('STL','ST LOUIS LAMBERT','WN AA DL UA','A B',168),
$A('MCI','KANSAS CITY','WN DL UA AA','A B C',169),
$A('IND','INDIANAPOLIS','DL AA UA WN','A B',170),
$A('CLE','CLEVELAND HOPKINS','UA AA DL WN','A B C',171),
$A('PIT','PITTSBURGH','AA DL UA WN','A B C',172),
$A('MKE','MILWAUKEE MITCHELL','AA DL UA WN','C D E',173),
$A('CMH','COLUMBUS JOHN GLENN','AA DL UA WN','A B C',174),
$A('JAX','JACKSONVILLE','AA DL UA WN','A B C',175),
$A('OMA','OMAHA EPPLEY','AA DL UA WN','A B C',176),
$A('HAV','HAVANA JOSE MARTI','CU AA','2 3',177),
$A('PTY','PANAMA TOCUMEN','CM AA DL UA LA','1 2',178),
$A('GIG','RIO DE JANEIRO GALEAO','LA G3 AA DL AF','1 2',179,'PARTIDAS · DEPARTURES'),
$A('BSB','BRASILIA','LA G3','1 2',180,'PARTIDAS · DEPARTURES'),
$A('SDQ','SANTO DOMINGO','DL AA JB','A B',181),
$A('SJU','SAN JUAN MUNOZ MARIN','AA DL UA JB','A B C',182),
$A('MBJ','MONTEGO BAY','AA DL UA BA','',183),
$A('LAS','LAS VEGAS H. REID','AA DL UA WN BA','A B C D',184),
$A('HNL','HONOLULU D.K. INOUYE','HA AA DL UA JL NH','1 2',185),
$A('ANC','ANCHORAGE','AS AA DL UA','A B C',186),
$A('NAS','NASSAU L. PINDLING','AA DL UA BA','C D',187),
$A('PUJ','PUNTA CANA','AA DL UA JB','A B',188),
$A('GDL','GUADALAJARA','AM AA DL UA','1 2',189,'SALIDAS · DEPARTURES'),
$A('MTY','MONTERREY','AM AA DL UA','A B C',190,'SALIDAS · DEPARTURES'),
$A('MDE','MEDELLIN JOSE MARIA','AV AA DL','D I',191),
$A('CTG','CARTAGENA R. NUNEZ','AV AA DL','',192),
$A('UIO','QUITO MARISCAL SUCRE','AV LA AA','',193),
$A('GYE','GUAYAQUIL','AV LA AA','',194),
$A('MVD','MONTEVIDEO CARRASCO','LA AV AA AF','',195),
$A('ASU','ASUNCION SILVIO PETTIROSSI','LA AV','',196),
/* ── OCEANIA EXPANDED ── */
$A('BNE','BRISBANE','QF VA SQ EK','D I',197),
$A('ADL','ADELAIDE','QF VA','T1 T2',198),
$A('CHC','CHRISTCHURCH','NZ QF VA','',199),
$A('WLG','WELLINGTON','NZ QF','',200),
$A('NAN','NADI','FJ QF NZ','',201),
$A('PPT','PAPEETE FAAA','TN AF','',202),
];

/* ═══ AIRPORT TIMEZONES ═══ */
const TZ={
/* Europe */
FRA:'Europe/Berlin',LHR:'Europe/London',AMS:'Europe/Amsterdam',CDG:'Europe/Paris',
FCO:'Europe/Rome',IST:'Europe/Istanbul',MUC:'Europe/Berlin',ZRH:'Europe/Zurich',
MAD:'Europe/Madrid',BCN:'Europe/Madrid',LIS:'Europe/Lisbon',VIE:'Europe/Vienna',
BRU:'Europe/Brussels',CPH:'Europe/Copenhagen',OSL:'Europe/Oslo',ARN:'Europe/Stockholm',
HEL:'Europe/Helsinki',DUB:'Europe/Dublin',MAN:'Europe/London',EDI:'Europe/London',
WAW:'Europe/Warsaw',PRG:'Europe/Prague',BUD:'Europe/Budapest',ATH:'Europe/Athens',
BER:'Europe/Berlin',HAM:'Europe/Berlin',DUS:'Europe/Berlin',MXP:'Europe/Rome',
GVA:'Europe/Zurich',NCE:'Europe/Paris',OTP:'Europe/Bucharest',TLV:'Asia/Jerusalem',
BGY:'Europe/Rome',SVO:'Europe/Moscow',LED:'Europe/Moscow',KBP:'Europe/Kiev',
OPO:'Europe/Lisbon',PMI:'Europe/Madrid',AGP:'Europe/Madrid',ALC:'Europe/Madrid',
TFS:'Atlantic/Canary',LTN:'Europe/London',STN:'Europe/London',LGW:'Europe/London',
GLA:'Europe/London',BHX:'Europe/London',LYS:'Europe/Paris',TLS:'Europe/Paris',
MRS:'Europe/Paris',SOF:'Europe/Sofia',ZAG:'Europe/Zagreb',BEG:'Europe/Belgrade',
RIX:'Europe/Riga',VNO:'Europe/Vilnius',TLL:'Europe/Tallinn',KEF:'Atlantic/Reykjavik',
/* Middle East */
DXB:'Asia/Dubai',DOH:'Asia/Qatar',AUH:'Asia/Dubai',JED:'Asia/Riyadh',
RUH:'Asia/Riyadh',MCT:'Asia/Muscat',BAH:'Asia/Bahrain',KWI:'Asia/Kuwait',
AMM:'Asia/Amman',BEY:'Asia/Beirut',
/* Africa */
CAI:'Africa/Cairo',NBO:'Africa/Nairobi',JNB:'Africa/Johannesburg',
CMN:'Africa/Casablanca',ADD:'Africa/Addis_Ababa',LOS:'Africa/Lagos',
CPT:'Africa/Johannesburg',DUR:'Africa/Johannesburg',DAR:'Africa/Dar_es_Salaam',
EBB:'Africa/Kampala',ACC:'Africa/Accra',ALG:'Africa/Algiers',TUN:'Africa/Tunis',
MRU:'Indian/Mauritius',
/* Asia */
HND:'Asia/Tokyo',NRT:'Asia/Tokyo',PEK:'Asia/Shanghai',PVG:'Asia/Shanghai',
CAN:'Asia/Shanghai',HKG:'Asia/Hong_Kong',ICN:'Asia/Seoul',SIN:'Asia/Singapore',
BKK:'Asia/Bangkok',DEL:'Asia/Kolkata',KUL:'Asia/Kuala_Lumpur',CGK:'Asia/Jakarta',
MNL:'Asia/Manila',TPE:'Asia/Taipei',KIX:'Asia/Tokyo',CTS:'Asia/Tokyo',
SGN:'Asia/Ho_Chi_Minh',CCU:'Asia/Kolkata',BOM:'Asia/Kolkata',BLR:'Asia/Kolkata',
MAA:'Asia/Kolkata',HYD:'Asia/Kolkata',CMB:'Asia/Colombo',DAC:'Asia/Dhaka',
KTM:'Asia/Kathmandu',RGN:'Asia/Yangon',HAN:'Asia/Ho_Chi_Minh',DPS:'Asia/Makassar',
HKT:'Asia/Bangkok',MLE:'Indian/Maldives',CTU:'Asia/Shanghai',SZX:'Asia/Shanghai',
XIY:'Asia/Shanghai',NKG:'Asia/Shanghai',WUH:'Asia/Shanghai',CKG:'Asia/Shanghai',
FUK:'Asia/Tokyo',NGO:'Asia/Tokyo',
/* Americas */
JFK:'America/New_York',EWR:'America/New_York',LAX:'America/Los_Angeles',
ORD:'America/Chicago',ATL:'America/New_York',SFO:'America/Los_Angeles',
MIA:'America/New_York',DFW:'America/Chicago',IAH:'America/Chicago',
SEA:'America/Los_Angeles',DEN:'America/Denver',BOS:'America/New_York',
YYZ:'America/Toronto',MEX:'America/Mexico_City',GRU:'America/Sao_Paulo',
EZE:'America/Argentina/Buenos_Aires',BOG:'America/Bogota',SCL:'America/Santiago',
LIM:'America/Lima',CUN:'America/Cancun',YVR:'America/Vancouver',
YUL:'America/Toronto',MSP:'America/Chicago',DTW:'America/New_York',
PHL:'America/New_York',CLT:'America/New_York',PHX:'America/Phoenix',
MCO:'America/New_York',SAN:'America/Los_Angeles',PDX:'America/Los_Angeles',
BWI:'America/New_York',DCA:'America/New_York',IAD:'America/New_York',
TPA:'America/New_York',BNA:'America/Chicago',AUS:'America/Chicago',
RDU:'America/New_York',SLC:'America/Denver',STL:'America/Chicago',
MCI:'America/Chicago',IND:'America/Indiana/Indianapolis',CLE:'America/New_York',
PIT:'America/New_York',MKE:'America/Chicago',CMH:'America/New_York',
JAX:'America/New_York',OMA:'America/Chicago',HAV:'America/Havana',
PTY:'America/Panama',GIG:'America/Sao_Paulo',BSB:'America/Sao_Paulo',
SDQ:'America/Santo_Domingo',SJU:'America/Puerto_Rico',MBJ:'America/Jamaica',
LAS:'America/Los_Angeles',HNL:'Pacific/Honolulu',ANC:'America/Anchorage',
NAS:'America/Nassau',PUJ:'America/Santo_Domingo',GDL:'America/Mexico_City',
MTY:'America/Monterrey',MDE:'America/Bogota',CTG:'America/Bogota',
UIO:'America/Guayaquil',GYE:'America/Guayaquil',MVD:'America/Montevideo',
ASU:'America/Asuncion',
/* Oceania */
SYD:'Australia/Sydney',MEL:'Australia/Melbourne',AKL:'Pacific/Auckland',
PER:'Australia/Perth',BNE:'Australia/Brisbane',ADL:'Australia/Adelaide',
CHC:'Pacific/Auckland',WLG:'Pacific/Auckland',NAN:'Pacific/Fiji',
PPT:'Pacific/Tahiti',
};

/* ═══ AIRPORT REGIONS ═══ */
const REGIONS={
'EUROPE':['FRA','LHR','AMS','CDG','FCO','IST','MUC','ZRH','MAD','BCN','LIS','VIE','BRU','CPH','OSL','ARN','HEL','DUB','MAN','EDI','WAW','PRG','BUD','ATH','BER','HAM','DUS','MXP','GVA','NCE','OTP','TLV','BGY','SVO','LED','KBP','OPO','PMI','AGP','ALC','TFS','LTN','STN','LGW','GLA','BHX','LYS','TLS','MRS','SOF','ZAG','BEG','RIX','VNO','TLL','KEF'],
'MIDDLE EAST':['DXB','DOH','AUH','JED','RUH','MCT','BAH','KWI','AMM','BEY'],
'AFRICA':['CAI','NBO','JNB','CMN','ADD','LOS','CPT','DUR','DAR','EBB','ACC','ALG','TUN','MRU'],
'ASIA':['HND','NRT','PEK','PVG','CAN','HKG','ICN','SIN','BKK','DEL','KUL','CGK','MNL','TPE','KIX','CTS','SGN','CCU','BOM','BLR','MAA','HYD','CMB','DAC','KTM','RGN','HAN','DPS','HKT','MLE','CTU','SZX','XIY','NKG','WUH','CKG','FUK','NGO'],
'AMERICAS':['JFK','EWR','LAX','ORD','ATL','SFO','MIA','DFW','IAH','SEA','DEN','BOS','YYZ','MEX','GRU','EZE','BOG','SCL','LIM','CUN','YVR','YUL','MSP','DTW','PHL','CLT','PHX','MCO','SAN','PDX','BWI','DCA','IAD','TPA','BNA','AUS','RDU','SLC','STL','MCI','IND','CLE','PIT','MKE','CMH','JAX','OMA','HAV','PTY','GIG','BSB','SDQ','SJU','MBJ','LAS','HNL','ANC','NAS','PUJ','GDL','MTY','MDE','CTG','UIO','GYE','MVD','ASU'],
'OCEANIA':['SYD','MEL','AKL','PER','BNE','ADL','CHC','WLG','NAN','PPT']
};
/* ═══ BULK AIRPORTS (800+) ═══ */
(function(){
const RA={NA:'WN AA DL UA',NA2:'WN AA DL UA',CA:'AC WS AA',MX:'AM VY AA',CB:'B6 AA DL JB',LA:'LA AV G3',
EU:'FR W6 EZY BA',EU2:'FR W6 EZY LH',EH:'LH BA AF TK',SC:'TK LH W6',ME:'EK QR TK SV',
AF:'ET EK TK KQ',AF2:'ET EK TK KQ',EA:'SQ CX NH JL',EA2:'SQ CX NH JL',SA:'AI SQ EK UK',OC:'QF VA JQ NZ'};
const RT={NA:'America/Chicago',NA2:'America/Chicago',CA:'America/Toronto',MX:'America/Mexico_City',
CB:'America/Puerto_Rico',LA:'America/Sao_Paulo',EU:'Europe/London',EU2:'Europe/Helsinki',
EH:'Europe/Berlin',SC:'Europe/Istanbul',ME:'Asia/Dubai',AF:'Africa/Lagos',AF2:'Africa/Lagos',
EA:'Asia/Singapore',EA2:'Asia/Singapore',SA:'Asia/Kolkata',OC:'Australia/Sydney'};
const TO={ABQ:'America/Denver',BDL:'America/New_York',BHM:'America/Chicago',BOI:'America/Boise',
BTV:'America/New_York',BUF:'America/New_York',BUR:'America/Los_Angeles',CAE:'America/New_York',
CAK:'America/New_York',CHS:'America/New_York',CVG:'America/New_York',DAL:'America/Chicago',
DAY:'America/New_York',ELP:'America/Denver',EVV:'America/Chicago',FAI:'America/Anchorage',
FAT:'America/Los_Angeles',FLL:'America/New_York',GEG:'America/Los_Angeles',HOU:'America/Chicago',
HSV:'America/Chicago',ICT:'America/Chicago',LIT:'America/Chicago',MDW:'America/Chicago',
MEM:'America/Chicago',MGM:'America/Chicago',MHT:'America/New_York',MOB:'America/Chicago',
MSN:'America/Chicago',MSY:'America/Chicago',OAK:'America/Los_Angeles',OGG:'Pacific/Honolulu',
OKC:'America/Chicago',ONT:'America/Los_Angeles',PBI:'America/New_York',PNS:'America/Chicago',
PSP:'America/Los_Angeles',PVD:'America/New_York',RIC:'America/New_York',RNO:'America/Los_Angeles',
ROC:'America/New_York',RSW:'America/New_York',SAT:'America/Chicago',SAV:'America/New_York',
SBA:'America/Los_Angeles',SDF:'America/New_York',SJC:'America/Los_Angeles',SMF:'America/Los_Angeles',
SNA:'America/Los_Angeles',SYR:'America/New_York',TLH:'America/New_York',TUL:'America/Chicago',
TUS:'America/Phoenix',TYS:'America/New_York',LBB:'America/Chicago',LEX:'America/New_York',
LNK:'America/Chicago',MAF:'America/Chicago',MFE:'America/Chicago',MYR:'America/New_York',
XNA:'America/Chicago',GRR:'America/New_York',GSO:'America/New_York',GSP:'America/New_York',
DSM:'America/Chicago',FAR:'America/Chicago',FSD:'America/Chicago',SHV:'America/Chicago',
BTR:'America/Chicago',COS:'America/Denver',CRP:'America/Chicago',ERI:'America/New_York',
FNT:'America/New_York',FWA:'America/New_York',GNV:'America/New_York',GPT:'America/Chicago',
GRB:'America/Chicago',MDT:'America/New_York',MRY:'America/Los_Angeles',ORF:'America/New_York',
RAP:'America/Denver',ROA:'America/New_York',SGF:'America/Chicago',SBN:'America/New_York',
YEG:'America/Edmonton',YHZ:'America/Halifax',YOW:'America/Toronto',YYC:'America/Edmonton',
YYJ:'America/Vancouver',YQB:'America/Toronto',YWG:'America/Winnipeg',YXE:'America/Edmonton',
ACA:'America/Mexico_City',PVR:'America/Mexico_City',SJD:'America/Mazatlan',TIJ:'America/Tijuana',
AUA:'America/Aruba',BGI:'America/Barbados',CUR:'America/Curacao',GCM:'America/Cayman',
KIN:'America/Jamaica',POS:'America/Port_of_Spain',SXM:'America/Lower_Princes',STT:'America/Virgin',
PTP:'America/Guadeloupe',FDF:'America/Martinique',UVF:'America/St_Lucia',
GUA:'America/Guatemala',SJO:'America/Costa_Rica',SAL:'America/El_Salvador',TGU:'America/Tegucigalpa',
MGA:'America/Managua',BZE:'America/Belize',
AEP:'America/Argentina/Buenos_Aires',COR:'America/Argentina/Cordoba',
BEL:'America/Belem',CNF:'America/Sao_Paulo',CWB:'America/Sao_Paulo',FLN:'America/Sao_Paulo',
FOR:'America/Fortaleza',POA:'America/Sao_Paulo',REC:'America/Recife',SSA:'America/Bahia',
VCP:'America/Sao_Paulo',CBB:'America/La_Paz',LPB:'America/La_Paz',
CLO:'America/Bogota',BAQ:'America/Bogota',
AAR:'Europe/Copenhagen',ABZ:'Europe/London',BFS:'Europe/London',BIO:'Europe/Madrid',
BLL:'Europe/Copenhagen',BLQ:'Europe/Rome',BOD:'Europe/Paris',BRE:'Europe/Berlin',
BRI:'Europe/Rome',BRS:'Europe/London',BSL:'Europe/Zurich',BTS:'Europe/Bratislava',
CAG:'Europe/Rome',CGN:'Europe/Berlin',CTA:'Europe/Rome',DME:'Europe/Moscow',
DTM:'Europe/Berlin',EIN:'Europe/Amsterdam',FAO:'Europe/Lisbon',FLR:'Europe/Rome',
GDN:'Europe/Warsaw',GOT:'Europe/Stockholm',GRZ:'Europe/Vienna',HAJ:'Europe/Berlin',
HER:'Europe/Athens',IBZ:'Europe/Madrid',INN:'Europe/Vienna',KRK:'Europe/Warsaw',
LCA:'Europe/Nicosia',LPA:'Atlantic/Canary',LUX:'Europe/Luxembourg',MLA:'Europe/Malta',
NAP:'Europe/Rome',NTE:'Europe/Paris',NUE:'Europe/Berlin',ORY:'Europe/Paris',
PSA:'Europe/Rome',SKG:'Europe/Athens',SPU:'Europe/Zagreb',STR:'Europe/Berlin',
SZG:'Europe/Vienna',TRN:'Europe/Rome',VCE:'Europe/Rome',VLC:'Europe/Madrid',
WRO:'Europe/Warsaw',ZAD:'Europe/Zagreb',DBV:'Europe/Zagreb',SAW:'Europe/Istanbul',
ADB:'Europe/Istanbul',ESB:'Europe/Istanbul',AYT:'Europe/Istanbul',TZX:'Europe/Istanbul',
DLM:'Europe/Istanbul',SJJ:'Europe/Sarajevo',TIA:'Europe/Tirane',SKP:'Europe/Skopje',
LJU:'Europe/Ljubljana',CRL:'Europe/Brussels',FNC:'Europe/Lisbon',RAK:'Africa/Casablanca',
SVQ:'Europe/Madrid',SCQ:'Europe/Madrid',BIQ:'Europe/Paris',RNS:'Europe/Paris',
AJA:'Europe/Paris',CFE:'Europe/Paris',
GYD:'Asia/Baku',TBS:'Asia/Tbilisi',EVN:'Asia/Yerevan',
SSH:'Africa/Cairo',HRG:'Africa/Cairo',LXR:'Africa/Cairo',
ABJ:'Africa/Abidjan',DKR:'Africa/Dakar',DSS:'Africa/Dakar',
ABV:'Africa/Lagos',KGL:'Africa/Kigali',LAD:'Africa/Luanda',
LUN:'Africa/Lusaka',HRE:'Africa/Harare',MPM:'Africa/Maputo',
WDH:'Africa/Windhoek',SEZ:'Indian/Mahe',ZNZ:'Africa/Dar_es_Salaam',
MBA:'Africa/Nairobi',FIH:'Africa/Kinshasa',
AMD:'Asia/Kolkata',ATQ:'Asia/Kolkata',BBI:'Asia/Kolkata',CJB:'Asia/Kolkata',
COK:'Asia/Kolkata',GAU:'Asia/Kolkata',GOI:'Asia/Kolkata',IXB:'Asia/Kolkata',
JAI:'Asia/Kolkata',LKO:'Asia/Kolkata',NAG:'Asia/Kolkata',PAT:'Asia/Kolkata',
TRV:'Asia/Kolkata',TRZ:'Asia/Kolkata',VNS:'Asia/Kolkata',
KHI:'Asia/Karachi',LHE:'Asia/Karachi',ISB:'Asia/Karachi',
CEB:'Asia/Manila',MFM:'Asia/Macau',PNH:'Asia/Phnom_Penh',REP:'Asia/Phnom_Penh',
CNX:'Asia/Bangkok',DMK:'Asia/Bangkok',USM:'Asia/Bangkok',
DLC:'Asia/Shanghai',HAK:'Asia/Shanghai',TAO:'Asia/Shanghai',TSN:'Asia/Shanghai',
XMN:'Asia/Shanghai',KMG:'Asia/Shanghai',CSX:'Asia/Shanghai',HGH:'Asia/Shanghai',
TNA:'Asia/Shanghai',CGO:'Asia/Shanghai',SHE:'Asia/Shanghai',HRB:'Asia/Shanghai',
KOJ:'Asia/Tokyo',OKA:'Asia/Tokyo',KMJ:'Asia/Tokyo',TAK:'Asia/Tokyo',
GMP:'Asia/Seoul',PUS:'Asia/Seoul',CJU:'Asia/Seoul',
CNS:'Australia/Brisbane',DRW:'Australia/Darwin',HBA:'Australia/Hobart',
OOL:'Australia/Brisbane',ZQN:'Pacific/Auckland',GUM:'Pacific/Guam',
APW:'Pacific/Apia',NOU:'Pacific/Noumea'};
const RN={NA:'AMERICAS',NA2:'AMERICAS',CA:'AMERICAS',MX:'AMERICAS',CB:'AMERICAS',LA:'AMERICAS',
EU:'EUROPE',EU2:'EUROPE',EH:'EUROPE',SC:'EUROPE',ME:'MIDDLE EAST',AF:'AFRICA',AF2:'AFRICA',
EA:'ASIA',EA2:'ASIA',SA:'ASIA',OC:'OCEANIA'};
const D={
NA:'ABQ ALBUQUERQUE,BDL HARTFORD,BHM BIRMINGHAM AL,BOI BOISE,BTV BURLINGTON VT,BUF BUFFALO,BUR BURBANK,CAE COLUMBIA SC,CAK AKRON CANTON,CHS CHARLESTON,COS COLORADO SPRINGS,CRP CORPUS CHRISTI,CVG CINCINNATI,DAL DALLAS LOVE,DAY DAYTON,DSM DES MOINES,ELP EL PASO,EVV EVANSVILLE,FAI FAIRBANKS,FAR FARGO,FAT FRESNO,FLL FORT LAUDERDALE,FNT FLINT,FSD SIOUX FALLS,FWA FORT WAYNE,GEG SPOKANE,GNV GAINESVILLE,GPT GULFPORT,GRB GREEN BAY,GRR GRAND RAPIDS,GSO GREENSBORO,GSP GREENVILLE SC,HOU HOUSTON HOBBY,HSV HUNTSVILLE,ICT WICHITA,LBB LUBBOCK,LEX LEXINGTON,LIT LITTLE ROCK,LNK LINCOLN,MAF MIDLAND,MDW CHICAGO MIDWAY,MEM MEMPHIS,MFE MCALLEN,MGM MONTGOMERY,MHT MANCHESTER NH,MOB MOBILE,MRY MONTEREY,MSN MADISON,MSY NEW ORLEANS,MYR MYRTLE BEACH,OAK OAKLAND,OGG MAUI,OKC OKLAHOMA CITY,ONT ONTARIO CA,ORF NORFOLK,PBI WEST PALM BEACH,PNS PENSACOLA,PSP PALM SPRINGS,PVD PROVIDENCE,RAP RAPID CITY,RIC RICHMOND,RNO RENO,ROA ROANOKE,ROC ROCHESTER,RSW FORT MYERS,SAT SAN ANTONIO,SAV SAVANNAH,SBA SANTA BARBARA,SBN SOUTH BEND,SDF LOUISVILLE,SGF SPRINGFIELD MO,SHV SHREVEPORT,SJC SAN JOSE CA,SMF SACRAMENTO,SNA ORANGE COUNTY,SRQ SARASOTA,SYR SYRACUSE,TLH TALLAHASSEE,TUL TULSA,TUS TUCSON,TVC TRAVERSE CITY,TYS KNOXVILLE,VPS DESTIN,XNA NW ARKANSAS,BTR BATON ROUGE,MDT HARRISBURG,ERI ERIE,ALB ALBANY NY,AVL ASHEVILLE,BHM BIRMINGHAM,CID CEDAR RAPIDS,CRW CHARLESTON WV,ILM WILMINGTON NC,ISP LONG ISLAND,JAN JACKSON MS,JNU JUNEAU,KOA KONA,LFT LAFAYETTE,LIH KAUAI,MLI QUAD CITIES,MOT MINOT,PIH POCATELLO,PSC TRI CITIES WA,RAP RAPID CITY,SBN SOUTH BEND,SPI SPRINGFIELD IL,TRI TRI CITIES TN,TYR TYLER,ABE LEHIGH VALLEY,ABI ABILENE,ACY ATLANTIC CITY,AGS AUGUSTA GA,AMA AMARILLO,AZO KALAMAZOO,BGR BANGOR,BIS BISMARCK,BIL BILLINGS,CHA CHATTANOOGA,DAB DAYTONA BEACH,ECP PANAMA CITY FL,FAY FAYETTEVILLE,HDN STEAMBOAT,HPN WESTCHESTER,ITO HILO,JAC JACKSON HOLE,SAF SANTA FE',
CA:'YEG EDMONTON,YHZ HALIFAX,YOW OTTAWA,YYC CALGARY,YYJ VICTORIA,YQB QUEBEC CITY,YWG WINNIPEG,YXE SASKATOON,YQR REGINA,YLW KELOWNA,YXU LONDON ON,YKF KITCHENER,YQM MONCTON,YFC FREDERICTON,YZF YELLOWKNIFE,YXY WHITEHORSE,YQT THUNDER BAY,YSB SUDBURY',
MX:'ACA ACAPULCO,CZM COZUMEL,HMO HERMOSILLO,MID MERIDA,OAX OAXACA,PVR PUERTO VALLARTA,SJD LOS CABOS,TIJ TIJUANA,ZIH IXTAPA,BJX LEON BAJIO,QRO QUERETARO,SLP SAN LUIS POTOSI,AGU AGUASCALIENTES,TAM TAMPICO,VER VERACRUZ,VSA VILLAHERMOSA,TLC TOLUCA,CUL CULIACAN,CEN CIUDAD OBREGON,LMM LOS MOCHIS,MZT MAZATLAN',
CB:'AUA ARUBA,BGI BARBADOS,CUR CURACAO,GCM GRAND CAYMAN,KIN KINGSTON,POS PORT OF SPAIN,SXM ST MAARTEN,STT ST THOMAS,PTP POINTE A PITRE,FDF FORT DE FRANCE,UVF ST LUCIA,ANU ANTIGUA,BON BONAIRE,DOM DOMINICA,GND GRENADA,SKB ST KITTS,SBH ST BARTHS,TAB TOBAGO,EIS TORTOLA,BDA BERMUDA,FPO FREEPORT,MHH MARSH HARBOUR,GGT EXUMA,ELH N ELEUTHERA,TCB TREASURE CAY',
LA:'AEP BUENOS AIRES AEP,COR CORDOBA,MDZ MENDOZA,BRC BARILOCHE,IGR IGUAZU,USH USHUAIA,ROS ROSARIO,NQN NEUQUEN,BEL BELEM,CNF BELO HORIZONTE,CWB CURITIBA,FLN FLORIANOPOLIS,FOR FORTALEZA,MAO MANAUS,POA PORTO ALEGRE,REC RECIFE,SSA SALVADOR,VCP CAMPINAS,NAT NATAL,MCZ MACEIO,GIG RIO GALEAO,CGB CUIABA,SLZ SAO LUIS,THE TERESINA,JPA JOAO PESSOA,CLO CALI,BAQ BARRANQUILLA,CBB COCHABAMBA,LPB LA PAZ,VVI SANTA CRUZ BO,CUZ CUSCO,AQP AREQUIPA,TRU TRUJILLO,PIU PIURA,IQT IQUITOS',
EH:'AAR AARHUS,ABZ ABERDEEN,BFS BELFAST,BIO BILBAO,BLL BILLUND,BLQ BOLOGNA,BOD BORDEAUX,BRE BREMEN,BRI BARI,BRS BRISTOL,BTS BRATISLAVA,CAG CAGLIARI,CGN COLOGNE,CTA CATANIA,DTM DORTMUND,EIN EINDHOVEN,FAO FARO,FLR FLORENCE,GDN GDANSK,GOT GOTHENBURG,GRZ GRAZ,HAJ HANNOVER,HER HERAKLION,IBZ IBIZA,INN INNSBRUCK,KRK KRAKOW,LCA LARNACA,LPA LAS PALMAS,LUX LUXEMBOURG,MLA MALTA,NAP NAPLES,NTE NANTES,NUE NUREMBERG,ORY PARIS ORLY,PSA PISA,SKG THESSALONIKI,SPU SPLIT,STR STUTTGART,SZG SALZBURG,TRN TURIN,VCE VENICE,VLC VALENCIA,WRO WROCLAW,ZAD ZADAR,DBV DUBROVNIK,SVQ SEVILLE,SCQ SANTIAGO COMP,RNS RENNES,BIQ BIARRITZ,AJA AJACCIO,BSL BASEL MULHOUSE,FNC MADEIRA,PDL PONTA DELGADA',
SC:'SAW ISTANBUL SABIHA,ADB IZMIR,ESB ANKARA,AYT ANTALYA,TZX TRABZON,DLM DALAMAN,BJV BODRUM,SJJ SARAJEVO,TIA TIRANA,SKP SKOPJE,LJU LJUBLJANA,CRL CHARLEROI,DME MOSCOW DME,KZN KAZAN,SVX YEKATERINBURG,UFA UFA,ROV ROSTOV ON DON,GYD BAKU,TBS TBILISI,EVN YEREVAN',
ME:'DMM DAMMAM,MED MEDINA,SSH SHARM EL SHEIKH,HRG HURGHADA,LXR LUXOR,BGW BAGHDAD,BSR BASRA,SLL SALALAH',
AF:'ABJ ABIDJAN,ABV ABUJA,DKR DAKAR,DSS BLAISE DIAGNE,KGL KIGALI,LAD LUANDA,LUN LUSAKA,HRE HARARE,MPM MAPUTO,WDH WINDHOEK,SEZ SEYCHELLES,ZNZ ZANZIBAR,MBA MOMBASA,FIH KINSHASA,BKO BAMAKO,OUA OUAGADOUGOU,COO COTONOU,LFW LOME,NDJ NDJAMENA,FNA FREETOWN,ROB MONROVIA,ENB ENTEBBE,JRO KILIMANJARO,MQX MEKELLE,BJR BAHIR DAR,DIR DIRE DAWA,TNR ANTANANARIVO,BLZ BLANTYRE,LLW LILONGWE,KRT KHARTOUM,ASW ASWAN',
EA:'CEB CEBU,MFM MACAU,PNH PHNOM PENH,REP SIEM REAP,CNX CHIANG MAI,DMK BANGKOK DMK,USM KO SAMUI,DLC DALIAN,HAK HAIKOU,TAO QINGDAO,TSN TIANJIN,XMN XIAMEN,KMG KUNMING,CSX CHANGSHA,HGH HANGZHOU,TNA JINAN,CGO ZHENGZHOU,SHE SHENYANG,HRB HARBIN,KOJ KAGOSHIMA,OKA OKINAWA,KMJ KUMAMOTO,GMP SEOUL GIMPO,PUS BUSAN,CJU JEJU,LPQ LUANG PRABANG,VTE VIENTIANE,MDL MANDALAY,BWN BRUNEI,SUB SURABAYA,JOG YOGYAKARTA,UPG MAKASSAR,BPN BALIKPAPAN,KNO MEDAN,PLM PALEMBANG,SRG SEMARANG',
SA:'AMD AHMEDABAD,ATQ AMRITSAR,BBI BHUBANESWAR,CJB COIMBATORE,COK KOCHI,GAU GUWAHATI,GOI GOA,IXB BAGDOGRA,JAI JAIPUR,LKO LUCKNOW,NAG NAGPUR,PAT PATNA,TRV TRIVANDRUM,TRZ TIRUCHIRAPPALLI,VNS VARANASI,IXR RANCHI,IXC CHANDIGARH,SXR SRINAGAR,VGA VIJAYAWADA,IXE MANGALORE,BHO BHOPAL,IDR INDORE,RAJ RAJKOT,KHI KARACHI,LHE LAHORE,ISB ISLAMABAD,PEW PESHAWAR,MUX MULTAN,SKT SIALKOT',
OC:'CNS CAIRNS,DRW DARWIN,HBA HOBART,OOL GOLD COAST,ZQN QUEENSTOWN,GUM GUAM,APW APIA,NOU NOUMEA,RAR RAROTONGA,SUV SUVA,HLZ HAMILTON NZ,NPE NAPIER,NSN NELSON,PMR PALMERSTON N,ROT ROTORUA,TRG TAURANGA,DUD DUNEDIN,IVC INVERCARGILL,TSV TOWNSVILLE,MKY MACKAY,PPP PROSERPINE,BDB BUNDABERG,LST LAUNCESTON,ASP ALICE SPRINGS,KTA KARRATHA',
NA2:'SFB ORLANDO SANFORD,PIE ST PETE CLEARWATER,PGD PUNTA GORDA,BLV BELLEVILLE,AZA MESA,STC ST CLOUD,BZN BOZEMAN,MSO MISSOULA,GFK GRAND FORKS,SUX SIOUX CITY,MCI KANSAS CITY,RFD ROCKFORD,LWB LEWISBURG,GJT GRAND JUNCTION,DRO DURANGO,MTJ MONTROSE,EGE EAGLE CO,HYS HAYS,GCK GARDEN CITY,DDC DODGE CITY,SPS WICHITA FALLS,TXK TEXARKANA,ELD EL DORADO,HOT HOT SPRINGS,FSM FORT SMITH,JLN JOPLIN,COU COLUMBIA MO,MKG MUSKEGON,ESC ESCANABA,PLN PELLSTON,CMX HOUGHTON,APN ALPENA,MBS MIDLAND MI,LAN LANSING,TOL TOLEDO,YNG YOUNGSTOWN,HTS HUNTINGTON WV,PKB PARKERSBURG,LBE LATROBE,AOO ALTOONA,ABE ALLENTOWN,IPT WILLIAMSPORT,ELM ELMIRA,BGM BINGHAMTON,ITH ITHACA,OGS OGDENSBURG,PLB PLATTSBURGH,SLK SARANAC LAKE,PQI PRESQUE ISLE',
EU2:'LPP LAPPEENRANTA,JYV JYVASKYLA,KUO KUOPIO,OUL OULU,RVN ROVANIEMI,TKU TURKU,TMP TAMPERE,SVG STAVANGER,HAU HAUGESUND,KRS KRISTIANSAND,BOO BODO,TRD TRONDHEIM,TOS TROMSO,BGO BERGEN,AES ALESUND,MMX MALMO,NRK NORRKOPING,VXO VAXJO,UME UMEA,LLA LULEA,RNB RONNEBY,KLR KALMAR,AAL AALBORG,BMA BROMMA,OSR OSTRAVA,RZE RZESZOW,KTW KATOWICE,POZ POZNAN,SZZ SZCZECIN,BRQ BRNO,IAS IASI,CLJ CLUJ,TSR TIMISOARA,SBZ SIBIU,SUJ SATU MARE,TGM TARGU MURES,CRV CROTONE,BDS BRINDISI,REG REGGIO CALABRIA,SUF LAMEZIA TERME,TRS TRIESTE,AOI ANCONA,PMF PARMA,TSF TREVISO,VRN VERONA,BGO BERGEN,GOA GENOA,CUF CUNEO,RMI RIMINI,PEG PERUGIA',
AF2:'OUA OUAGADOUGOU,BKO BAMAKO,COO COTONOU,LFW LOME,NDJ NDJAMENA,FNA FREETOWN,ROB MONROVIA,JRO KILIMANJARO,TNR ANTANANARIVO,BLZ BLANTYRE,LLW LILONGWE,KRT KHARTOUM,ASW ASWAN,MTS MANZINI,GBE GABORONE,PLZ PORT ELIZABETH,BFN BLOEMFONTEIN,ELS EAST LONDON,VFA VICTORIA FALLS,LVI LIVINGSTONE,BUQ BULAWAYO,MUB MAUN,SKR SHAKISO,CMR COLMAR,BJL BANJUL,NKC NOUAKCHOTT,PRI PRASLIN,PTG POLOKWANE,MQP KRUGER MPUMALANGA,LBV LIBREVILLE,PNR POINTE NOIRE,DLA DOUALA,YAO YAOUNDE,NIM NIAMEY,JIB DJIBOUTI',
EA2:'NAH NAH TRANG,DAD DA NANG,HUI HUE,VDO VAN DON,HPH HAI PHONG,BKI KOTA KINABALU,KCH KUCHING,LGK LANGKAWI,PEN PENANG,SZB KUALA LUMPUR SUBANG,IPH IPOH,MYY MIRI,TWU TAWAU,JHB JOHOR BAHRU,SBW SIBU,BTU BINTULU,KBR KOTA BHARU,TGG KUALA TERENGGANU,CRK CLARK,ILO ILOILO,DVO DAVAO,ZAM ZAMBOANGA,BCD BACOLOD,TAG BOHOL,MPH CATICLAN,PPS PUERTO PRINCESA,CGY CAGAYAN DE ORO,SOC SOLO,YIA YOGYAKARTA NEW,LOP LOMBOK,MDC MANADO,AMQ AMBON,TIM TIMIKA,DJJ JAYAPURA,BDO BANDUNG,PDG PADANG,PKU PEKANBARU,BTJ BANDA ACEH,TAE DAEGU,KWJ GWANGJU,RSU YEOSU,WJU WONJU,HIN JINJU,MWX MUAN,USN ULSAN,YNJ YANJI,WNZ WENZHOU,YNT YANTAI,WEH WEIHAI,LYA LUOYANG,XNN XINING,LHW LANZHOU,INC YINCHUAN,HET HOHHOT,NAY NANYANG'

};
let sd=300;const ex=new Set(AP.map(a=>a.c));
for(const rk in D){D[rk].split(',').forEach(s=>{
s=s.trim();if(!s)return;const i=s.indexOf(' ');if(i<0)return;
const c=s.substring(0,i),n=s.substring(i+1);
if(ex.has(c))return;ex.add(c);
AP.push($A(c,n,RA[rk]||'AA DL UA','',sd++));
if(!TZ[c])TZ[c]=TO[c]||RT[rk]||'UTC';
const rn=RN[rk];if(rn&&REGIONS[rn]&&!REGIONS[rn].includes(c))REGIONS[rn].push(c);
});}
})();

const AP_REGION={};
for(const r in REGIONS)REGIONS[r].forEach(c=>AP_REGION[c]=r);

/* ═══ AIRLINE ROUTE NETWORKS ═══ */
function $N(h,d){return{h:h.split(' '),d:d.split(' ')}}
const NET={
LH:$N('FRA MUC','LHR CDG AMS FCO IST ZRH MAD BCN LIS VIE BRU CPH OSL ARN HEL DUB WAW PRG BUD ATH DXB DOH CAI JNB NBO ADD NRT HND PEK PVG HKG ICN SIN BKK DEL BOM KUL JFK EWR LAX ORD ATL SFO MIA DFW IAH SEA DEN BOS YYZ MEX GRU EZE BOG SYD BER HAM DUS GVA NCE OTP TLV MCT BAH RUH KWI MAA BLR SGN CTU TPE'),
BA:$N('LHR','FRA CDG AMS FCO IST ZRH MAD BCN LIS VIE BRU CPH HEL DUB MAN EDI WAW PRG ATH DXB DOH CAI JNB NBO ADD NRT HND PEK PVG HKG ICN SIN BKK DEL BOM KUL JFK EWR LAX ORD ATL MIA DFW BOS YYZ MEX GRU EZE SYD BER MXP TLV RUH JED AUH'),
AF:$N('CDG','LHR FRA AMS FCO IST ZRH MAD BCN LIS VIE BRU CPH OSL HEL DUB WAW PRG ATH DXB DOH CAI JNB NBO ADD CMN NRT HND PEK PVG HKG ICN SIN BKK DEL BOM KUL JFK LAX ORD ATL MIA SFO YYZ MEX GRU EZE BOG SCL NCE MXP BER TLV'),
KL:$N('AMS','LHR FRA CDG FCO IST MAD BCN LIS VIE BRU CPH OSL ARN HEL DUB WAW PRG BUD ATH DXB DOH CAI JNB NBO NRT HND PEK PVG HKG ICN SIN BKK DEL BOM KUL CGK JFK LAX ORD ATL SFO MIA IAH YYZ MEX GRU EZE BOG SYD'),
TK:$N('IST','LHR FRA CDG AMS FCO ZRH MAD BCN LIS VIE BRU CPH OSL ARN HEL DUB MAN WAW PRG BUD ATH DXB DOH CAI JNB NBO ADD CMN LOS NRT HND PEK PVG CAN HKG ICN SIN BKK DEL BOM KUL CGK MNL TPE JFK EWR LAX ORD ATL SFO MIA DFW IAH BOS YYZ MEX GRU EZE BOG SCL LIM SYD ADB TLV RUH JED AUH MCT BAH KWI MAA BLR HAN SGN CTU SZX'),
EK:$N('DXB','LHR FRA CDG AMS FCO IST ZRH MAD BCN LIS VIE BRU CPH OSL ARN HEL DUB MAN WAW PRG BUD ATH DOH CAI JNB NBO ADD CMN LOS NRT HND PEK PVG CAN HKG ICN SIN BKK DEL BOM KUL CGK MNL TPE KIX JFK EWR LAX ORD ATL SFO MIA DFW IAH SEA DEN BOS YYZ MEX GRU EZE BOG SYD MEL AKL PER MXP BER GVA NCE TLV RUH JED AUH MCT BAH KWI MAA BLR HAN SGN CTU SZX CMB MLE HKT DPS'),
QR:$N('DOH','LHR FRA CDG AMS FCO IST ZRH MAD BCN LIS VIE BRU CPH ARN HEL ATH DXB CAI JNB NBO ADD LOS NRT HND PEK PVG HKG ICN SIN BKK DEL BOM KUL CGK MNL TPE JFK LAX ORD MIA DFW IAH BOS YYZ GRU SYD MEL AKL MXP BER TLV RUH JED AUH MCT BAH KWI MAA BLR SGN CMB MLE DPS'),
SQ:$N('SIN','LHR FRA CDG AMS FCO IST ZRH CPH MAN DXB DOH NRT HND PEK PVG CAN HKG ICN BKK DEL BOM KUL CGK MNL TPE KIX JFK LAX ORD SFO SEA YYZ SYD MEL AKL PER MXP GVA MAA BLR SGN HAN CTU SZX CMB MLE HKT DPS'),
CX:$N('HKG','LHR FRA AMS CDG DXB DOH NRT HND PEK PVG ICN SIN BKK DEL BOM KUL CGK MNL TPE KIX JFK LAX ORD SFO SEA BOS YYZ SYD MEL AKL PER MXP SGN HAN CTU SZX DPS'),
NH:$N('HND NRT','LHR FRA CDG AMS MUC ZRH DXB DOH PEK PVG HKG ICN SIN BKK DEL KUL CGK MNL TPE KIX CTS JFK LAX ORD SFO SEA IAH YYZ MEX SYD HAN SGN'),
JL:$N('HND NRT','LHR CDG FRA DXB PEK PVG HKG ICN SIN BKK DEL KUL MNL TPE KIX CTS JFK LAX ORD BOS SFO SEA SYD'),
AA:$N('DFW ORD JFK MIA LAX','LHR CDG FRA MAD BCN NRT HND HKG ICN PEK PVG SIN BKK DEL DXB DOH SYD GRU EZE BOG SCL LIM MEX CUN YYZ EWR ATL SFO IAH SEA DEN BOS PHL MSP DTW CLT PHX MCO SAN PDX YVR YUL HAV PTY'),
DL:$N('ATL JFK LAX SEA','LHR CDG FRA AMS FCO IST MUC DXB NRT HND PEK PVG HKG ICN SIN BKK SYD GRU EZE BOG MEX CUN YYZ ORD MIA DFW IAH DEN BOS SFO EWR PHL MSP DTW CLT PHX MCO SAN PDX YVR YUL HAV PTY'),
UA:$N('ORD EWR SFO IAH LAX DEN','LHR FRA CDG AMS FCO IST MUC ZRH DXB DOH NRT HND PEK PVG HKG ICN SIN BKK DEL SYD MEL GRU EZE BOG MEX CUN YYZ ATL MIA DFW SEA BOS JFK PHL MSP DTW CLT PHX MCO SAN PDX YVR YUL'),
QF:$N('SYD MEL','LHR DXB SIN HKG NRT HND BKK DEL JFK LAX SFO AKL PER DPS'),
KE:$N('ICN','LHR FRA CDG AMS FCO IST DXB NRT HND PEK PVG CAN HKG SIN BKK DEL KUL CGK MNL TPE KIX JFK LAX ORD ATL SFO SEA YYZ SYD MEL GRU SGN HAN'),
OZ:$N('ICN','FRA LHR CDG IST DXB NRT HND PEK PVG CAN HKG SIN BKK KUL MNL TPE KIX JFK LAX SFO SEA SYD SGN HAN'),
CA:$N('PEK','LHR FRA CDG AMS FCO IST ZRH DXB NRT HND HKG ICN SIN BKK DEL BOM KUL PVG CAN CTU SZX JFK LAX SFO ORD YYZ SYD MEL GRU MXP GVA'),
MU:$N('PVG','LHR FRA CDG AMS FCO IST DXB NRT HND HKG ICN SIN BKK DEL BOM KUL CGK PEK CAN CTU SZX JFK LAX SFO ORD SYD MEL MXP'),
CZ:$N('CAN','LHR FRA CDG AMS FCO IST DXB NRT HKG ICN SIN BKK DEL BOM KUL CGK PEK PVG CTU SZX JFK LAX SYD MEL NBO ADD'),
TG:$N('BKK','LHR FRA CDG AMS DXB NRT HND PEK PVG HKG ICN SIN DEL BOM KUL CGK MNL TPE KIX JFK LAX SYD MEL AKL MAA BLR SGN HAN CMB MLE HKT DPS'),
MH:$N('KUL','LHR DXB DOH IST NRT HND PEK PVG HKG ICN SIN BKK DEL BOM CGK MNL TPE SYD MEL AKL SGN HAN CMB MLE HKT DPS'),
GA:$N('CGK','SIN KUL BKK HKG NRT HND PEK PVG ICN AMS DXB SYD MEL DPS SGN'),
CI:$N('TPE','LHR FRA AMS DXB NRT HND PEK PVG HKG ICN SIN BKK KUL CGK MNL KIX JFK LAX SFO SYD MEL AKL SGN HAN'),
BR:$N('TPE','LHR FRA NRT HND PEK PVG HKG ICN SIN BKK KUL MNL KIX JFK LAX SFO SYD'),
VN:$N('SGN HAN','LHR FRA CDG NRT HND PEK PVG HKG ICN SIN BKK KUL DEL SYD MEL'),
PR:$N('MNL','SIN HKG NRT HND PEK PVG ICN BKK KUL DXB DOH JFK LAX SFO SYD'),
AI:$N('DEL BOM','LHR FRA CDG AMS SIN HKG NRT HND BKK KUL DXB DOH JFK EWR ORD SFO YYZ SYD MEL CCU MAA BLR CMB MLE'),
ET:$N('ADD','LHR FRA CDG IST DXB DOH CAI JNB NBO LOS NRT HND PEK PVG HKG SIN BKK DEL BOM KUL JFK LAX ORD YYZ GRU'),
SA:$N('JNB','LHR FRA CAI NBO ADD CMN LOS'),
EY:$N('AUH','LHR FRA CDG AMS FCO IST ZRH DXB NRT HND PEK PVG HKG ICN SIN BKK DEL BOM KUL CGK JFK LAX ORD SYD MEL MXP'),
SV:$N('JED RUH','LHR FRA CDG IST CAI DXB DOH AUH KWI BAH DEL BOM KUL SIN BKK CGK'),
FZ:$N('DXB','LHR AMS IST CAI JNB NBO CMN DEL BOM KUL SIN BKK CGK MNL'),
LX:$N('ZRH','LHR FRA CDG AMS FCO IST MAD BCN LIS VIE BRU CPH DUB ATH DXB DOH CAI NRT HND PEK PVG HKG SIN BKK DEL JFK LAX SFO ORD YYZ GRU SYD MXP BER GVA'),
IB:$N('MAD BCN','LHR FRA CDG AMS FCO IST LIS DXB DOH NRT PEK PVG HKG JFK MIA ORD LAX MEX GRU EZE BOG SCL LIM CUN'),
SK:$N('CPH OSL ARN','LHR FRA CDG AMS FCO IST ZRH MAD LIS VIE BRU HEL DUB WAW PRG ATH NRT PEK SIN BKK JFK ORD'),
AY:$N('HEL','LHR FRA CDG AMS FCO IST ZRH MAD LIS VIE BRU CPH OSL ARN DUB WAW PRG ATH DXB DOH NRT HND PEK PVG HKG SIN BKK DEL JFK ORD SFO'),
OS:$N('VIE','LHR FRA CDG AMS FCO IST ZRH MAD BCN LIS BRU CPH DUB WAW PRG BUD ATH DXB DOH CAI NRT PEK PVG'),
TP:$N('LIS','LHR FRA CDG AMS FCO MAD BCN VIE BRU CPH DUB ATH DXB DOH CAI JNB NBO ADD CMN JFK EWR ORD MIA GRU EZE BOG SCL'),
VY:$N('BCN','LHR FRA CDG AMS FCO MAD LIS VIE BRU CPH DUB ATH'),
SN:$N('BRU','LHR FRA CDG AMS FCO IST MAD BCN LIS VIE CPH DUB WAW PRG ATH DXB DOH CAI JNB NBO ADD'),
EI:$N('DUB','LHR FRA CDG AMS FCO IST MAD BCN LIS VIE BRU CPH JFK EWR BOS ORD'),
LO:$N('WAW','LHR FRA CDG AMS FCO IST ZRH MAD BCN LIS VIE BRU CPH DUB PRG BUD ATH DXB DOH CAI NRT PEK PVG'),
OK:$N('PRG','LHR FRA CDG AMS FCO IST ZRH MAD BCN VIE BRU CPH DUB WAW BUD ATH DXB DOH'),
W6:$N('BUD','LHR FRA CDG AMS FCO IST MAD BCN LIS VIE BRU CPH DUB WAW PRG ATH DXB'),
A3:$N('ATH','LHR FRA CDG AMS FCO IST ZRH MAD BCN LIS VIE BRU CPH DUB WAW PRG BUD DXB DOH CAI'),
MS:$N('CAI','LHR FRA CDG AMS FCO IST MAD ATH DXB DOH JNB NBO JED RUH KWI NRT SIN BKK JFK'),
KQ:$N('NBO','LHR FRA CDG AMS IST DXB DOH JNB ADD LOS CAI CMN DEL BOM BKK'),
AT:$N('CMN','LHR FRA CDG AMS FCO IST MAD BCN LIS BRU DXB DOH CAI JFK ORD YYZ GRU'),
W3:$N('LOS','LHR FRA CDG AMS IST DXB DOH JNB NBO ADD CAI'),
AC:$N('YYZ YUL','LHR FRA CDG AMS FCO IST ZRH DXB DOH NRT HND PEK PVG HKG ICN SIN BKK DEL JFK LAX SFO ORD MIA SEA DEN BOS EWR MEX GRU EZE BOG SYD MEL'),
AM:$N('MEX','LHR FRA CDG MAD BCN NRT PEK PVG JFK LAX ORD MIA DFW IAH SFO GRU EZE BOG SCL LIM CUN HAV PTY'),
LA:$N('SCL GRU','LHR FRA CDG MAD BCN FCO NRT PEK PVG SYD MEL AKL JFK LAX MIA ORD MEX EZE BOG LIM CUN'),
G3:$N('GRU','LHR FRA CDG MAD MIA JFK ORD EZE BOG SCL LIM MEX'),
AR:$N('EZE','LHR FRA CDG MAD BCN FCO MIA JFK GRU SCL BOG LIM MEX'),
AV:$N('BOG','LHR FRA MAD JFK MIA LAX GRU EZE SCL LIM MEX CUN'),
WS:$N('YYZ YVR YUL','LHR FRA CDG AMS DXB NRT HND JFK LAX ORD MIA SFO SEA DEN BOS MEX CUN'),
VS:$N('LHR','JFK LAX SFO ORD MIA IAH SEA BOS ATL DFW DEN JNB'),
VA:$N('SYD MEL','AKL PER DPS'),
NZ:$N('AKL','LHR SIN HKG NRT BKK SYD MEL PER JFK LAX SFO'),
AK:$N('KUL','SIN BKK CGK MNL TPE DPS HKT CMB'),
UK:$N('DEL BOM','SIN DXB LHR BKK HKG MAA BLR CCU CMB'),
HX:$N('HKG','NRT HND PEK PVG CAN ICN SIN BKK KUL CGK MNL TPE'),
AZ:$N('FCO MXP','LHR FRA CDG AMS IST MAD BCN LIS VIE BRU ATH DXB CAI NRT HND JFK LAX MIA ORD GRU EZE'),
XQ:$N('IST ADB','FRA MUC DUS HAM BER AMS LHR CDG'),
};

/* DS_MAP for O(1) lookup by IATA code */
const DS_MAP={};DS.forEach(d=>{DS_MAP[d[1]]=d});
/* Cell dimension cache — set once after first layout, reused by flip engine */
let CELL_W=0,CELL_H=0;

/* Same-metro airport pairs — no flights between these */
const SAME_METRO={
  'JFK':['EWR'],'EWR':['JFK'],
  'HND':['NRT'],'NRT':['HND']
};

/* Build route pool for an airport: returns [[airline, destination],...] */
const _routeCache={};
function getRoutes(ap){
  if(_routeCache[ap.c])return _routeCache[ap.c];
  const routes=[];
  ap.al.forEach(al=>{
    const net=NET[al];
    if(!net){
      DS.forEach(d=>{if(d[1]!==ap.c&&fnHash(d[1].charCodeAt(0),al.charCodeAt(0))%6===0)routes.push([al,d])});
      return;
    }
    const isHub=net.h.includes(ap.c);
    if(isHub){
      net.d.forEach(code=>{
        if(code!==ap.c){const ds=DS_MAP[code];if(ds)routes.push([al,ds])}
      });
    }else{
      /* Non-hub: only fly to this airline's hub(s) — no phantom spoke-spoke routes */
      net.h.forEach(hc=>{
        if(hc!==ap.c){const ds=DS_MAP[hc];if(ds)routes.push([al,ds])}
      });
    }
  });
  /* Filter same-metro absurdities (e.g. EWR↔JFK, HND↔NRT) */
  const excl=SAME_METRO[ap.c];
  if(excl){
    for(let i=routes.length-1;i>=0;i--){
      if(excl.includes(routes[i][1][1])) routes.splice(i,1);
    }
  }
  /* Deterministic shuffle to avoid duplicate clusters */
  for(let i=routes.length-1;i>0;i--){
    const j=fnHash(i,ap.sd)%(i+1);
    const tmp=routes[i];routes[i]=routes[j];routes[j]=tmp;
  }
  _routeCache[ap.c]=routes;
  return routes;
}

/* ═══ FLIGHT GENERATION ═══ */
function p2(n){return n.toString().padStart(2,'0')}

/* Multiplicative hash for flight number variety */
function fnHash(i,seed){
  let h=((i+1)*2654435761+(seed+1)*2246822519)>>>0;
  h=((h>>>16)^h)*0x45d9f3b>>>0;
  return h;
}

/* Airline flight number ranges — [min, max] matching real numbering conventions */
const FN_RNG={
LH:[100,4800],BA:[1,2600],AF:[1,3800],KL:[400,2800],
TK:[1,1980],EK:[1,680],QR:[1,780],SQ:[1,960],
CX:[200,880],NH:[1,980],JL:[1,780],AA:[1,2800],
DL:[1,2800],UA:[1,2500],QF:[1,880],KE:[1,960],
OZ:[100,980],CA:[100,1950],MU:[500,5800],CZ:[300,3800],
TG:[300,2800],MH:[1,780],GA:[200,980],CI:[1,960],
BR:[1,780],VN:[300,1950],PR:[100,880],AI:[100,980],
ET:[100,780],SA:[200,780],EY:[1,680],SV:[100,1950],
FZ:[1,980],LX:[1,1980],IB:[100,3680],SK:[100,980],
AY:[1,980],OS:[1,980],TP:[200,1950],VY:[1000,6500],
SN:[1,3800],EI:[100,980],LO:[1,780],OK:[100,780],
W6:[2000,9800],A3:[100,680],MS:[100,780],KQ:[100,780],
AT:[200,980],W3:[100,580],AC:[1,980],AM:[1,980],
LA:[600,1950],G3:[1000,2980],AR:[1100,1980],AV:[1,980],
WS:[1,980],VS:[1,460],VA:[1,980],NZ:[1,960],
AK:[300,1980],UK:[300,980],HX:[200,880],AZ:[100,680],
XQ:[100,980],
};

/* Famous real flight numbers: 'AL:FROM:TO' → flight number */
const FAMOUS={
'LH:FRA:JFK':400,'LH:FRA:EWR':410,'LH:FRA:ORD':430,'LH:FRA:LAX':450,
'LH:FRA:SFO':454,'LH:FRA:MIA':460,'LH:FRA:IAH':440,'LH:FRA:NRT':710,
'LH:FRA:HND':716,'LH:FRA:PEK':720,'LH:FRA:PVG':728,'LH:FRA:HKG':796,
'LH:FRA:SIN':778,'LH:FRA:BKK':772,'LH:FRA:DEL':760,'LH:FRA:BOM':764,
'LH:FRA:GRU':502,'LH:FRA:EZE':510,'LH:FRA:DXB':630,'LH:FRA:DOH':640,
'LH:FRA:JNB':572,'LH:FRA:SYD':790,'LH:FRA:ICN':712,
'LH:MUC:JFK':414,'LH:MUC:ORD':434,'LH:MUC:LAX':452,
'BA:LHR:JFK':1,'BA:LHR:LAX':269,'BA:LHR:SFO':285,'BA:LHR:ORD':295,
'BA:LHR:MIA':209,'BA:LHR:BOS':213,'BA:LHR:DFW':193,
'BA:LHR:NRT':5,'BA:LHR:HND':7,'BA:LHR:HKG':27,'BA:LHR:SIN':11,
'BA:LHR:BKK':9,'BA:LHR:DEL':257,'BA:LHR:SYD':15,'BA:LHR:PEK':39,
'BA:LHR:DXB':107,'BA:LHR:DOH':125,'BA:LHR:JNB':55,'BA:LHR:GRU':247,
'AF:CDG:JFK':1,'AF:CDG:LAX':66,'AF:CDG:NRT':275,'AF:CDG:HKG':188,
'AF:CDG:SIN':256,'AF:CDG:PEK':128,'AF:CDG:GRU':456,'AF:CDG:DXB':662,
'EK:DXB:LHR':1,'EK:DXB:JFK':201,'EK:DXB:LAX':215,'EK:DXB:SFO':225,
'EK:DXB:SYD':412,'EK:DXB:NRT':318,'EK:DXB:HKG':384,'EK:DXB:SIN':354,
'EK:DXB:BKK':372,'EK:DXB:CDG':71,'EK:DXB:FRA':45,'EK:DXB:AMS':91,
'EK:DXB:FCO':95,'EK:DXB:GRU':261,'EK:DXB:ORD':235,
'QR:DOH:LHR':1,'QR:DOH:JFK':701,'QR:DOH:LAX':739,'QR:DOH:CDG':39,
'SQ:SIN:LHR':308,'SQ:SIN:JFK':22,'SQ:SIN:LAX':37,'SQ:SIN:SFO':1,
'SQ:SIN:NRT':638,'SQ:SIN:HKG':856,'SQ:SIN:SYD':211,'SQ:SIN:FRA':326,
'CX:HKG:LHR':251,'CX:HKG:JFK':840,'CX:HKG:LAX':880,'CX:HKG:SIN':715,
'CX:HKG:NRT':500,'CX:HKG:SYD':101,'CX:HKG:BKK':701,
'NH:NRT:JFK':10,'NH:NRT:LAX':6,'NH:NRT:ORD':12,'NH:NRT:SFO':8,
'NH:HND:LHR':211,'NH:HND:FRA':223,'NH:HND:CDG':215,'NH:HND:SIN':843,
'JL:NRT:JFK':4,'JL:NRT:LAX':62,'JL:NRT:ORD':10,'JL:NRT:LHR':41,
'JL:HND:LHR':43,'JL:HND:CDG':45,'JL:HND:SIN':35,'JL:HND:BKK':31,
'AA:JFK:LHR':100,'AA:DFW:LHR':50,'AA:MIA:LHR':56,'AA:LAX:NRT':169,
'AA:DFW:NRT':175,'AA:JFK:NRT':153,'AA:ORD:LHR':86,
'DL:ATL:LHR':1,'DL:JFK:LHR':7,'DL:LAX:NRT':283,'DL:ATL:NRT':295,
'DL:JFK:CDG':264,'DL:ATL:CDG':78,'DL:JFK:AMS':46,
'UA:EWR:LHR':16,'UA:SFO:LHR':900,'UA:ORD:LHR':930,'UA:IAH:LHR':882,
'UA:SFO:NRT':837,'UA:SFO:SIN':15,'UA:SFO:HKG':877,'UA:SFO:PVG':857,
'QF:SYD:LHR':1,'QF:SYD:LAX':11,'QF:SYD:DFW':7,'QF:SYD:SIN':231,
'QF:MEL:LAX':93,'QF:SYD:HKG':127,'QF:SYD:NRT':21,
'KE:ICN:JFK':81,'KE:ICN:LAX':11,'KE:ICN:NRT':701,'KE:ICN:LHR':907,
'CA:PEK:JFK':981,'CA:PEK:LAX':983,'CA:PEK:LHR':937,'CA:PEK:FRA':931,
'TK:IST:JFK':1,'TK:IST:LAX':9,'TK:IST:LHR':1991,'TK:IST:CDG':1823,
'AC:YYZ:LHR':848,'AC:YYZ:FRA':872,'AC:YYZ:NRT':1,'AC:YYZ:HKG':15,
};

/* Generate flight number: famous DB → airline range → fallback */
function genFlightNum(i,seed,al,from,to,firstCycle){
  if(firstCycle){
    let famous=FAMOUS[al+':'+from+':'+to];
    if(famous!==undefined) return famous.toString().padStart(W_FN,' ');
    /* Reverse direction: conventional return flight = number + 1 */
    famous=FAMOUS[al+':'+to+':'+from];
    if(famous!==undefined) return (famous+1).toString().padStart(W_FN,' ');
  }
  const h=fnHash(i,seed);
  const rng=FN_RNG[al];
  if(rng){
    const num=rng[0]+h%(rng[1]-rng[0]+1);
    return num.toString().padStart(W_FN,' ');
  }
  return (1+h%9999).toString().padStart(W_FN,' ');
}

function genF(ap,count,arrMode,startMin){
  const now=new Date();
  const curTotal=now.getHours()*60+now.getMinutes();
  const linear=(startMin!==undefined);
  const routes=getRoutes(ap);
  if(!routes.length){/* Fallback if no routes */
    const pool=DS.filter(d=>d[1]!==ap.c);
    for(let i=0;i<count;i++){const hh=fnHash(i,ap.sd);routes.push([ap.al[hh%ap.al.length],pool[hh%pool.length]])}
  }
  const fl=[];

  /* Start time: linear from startMin, or ~1h before now */
  let t=linear?startMin:curTotal-55-(ap.sd%8)*2;
  if(!linear&&t<0)t+=1440;

  for(let i=0;i<count;i++){
    const hh=fnHash(i,ap.sd);

    /* Airline & destination — cycle through shuffled routes (no duplicates) */
    const route=routes[i%routes.length];
    const al=route[0];
    const dt=route[1];

    /* Round time to 5-min marks like real schedules */
    const rt=Math.round(t/5)*5;
    const hour=Math.floor(rt/60)%24;
    const min=rt%60;

    /* Gate: prefix + number */
    const gx=ap.gp.length?ap.gp[hh%ap.gp.length]:'';
    const gn=(1+hh%60).toString();

    /* Flight number — famous on first cycle, airline-range on repeats */
    const fnFrom=arrMode?dt[1]:ap.c, fnTo=arrMode?ap.c:dt[1];
    const fn=genFlightNum(i,ap.sd,al,fnFrom,fnTo,i<routes.length);

    /* Status based on time proximity to now */
    let diff=t-curTotal;
    if(!linear){if(diff>720)diff-=1440;if(diff<-720)diff+=1440}

    let s;
    if(arrMode){
      /* ── Arrival statuses ── */
      if(diff<-15)       s='LANDED';
      else if(diff<-5)   s=(hh%7===0)?'DELAYED':'LANDED';
      else if(diff<=0)   s='LANDED';
      else if(diff<=10)  s='ARRIVING';
      else if(diff<=25)  s=(hh%4===0)?'ON TIME':'EXPECTED';
      else if(diff<=60)  s=(hh%6===0)?'EXPECTED':'ON TIME';
      else               s=(hh%18===0)?'DELAYED':'ON TIME';
      if(s!=='LANDED'&&hh%67===0) s='CANCELLED';
    }else{
      /* ── Departure statuses ── */
      if(diff<-20)       s='DEPARTED';
      else if(diff<-10)  s=(hh%7===0)?'DELAYED':'DEPARTED';
      else if(diff<=-3)  s=(hh%5===0)?'LAST CALL':'BOARDING';
      else if(diff<=0)   s='BOARDING';
      else if(diff<=12)  s=(hh%3===0)?'GATE OPEN':'BOARDING';
      else if(diff<=30)  s=(hh%4===0)?'ON TIME':'GATE OPEN';
      else if(diff<=60)  s=(hh%6===0)?'GATE OPEN':'ON TIME';
      else               s=(hh%18===0)?'DELAYED':'ON TIME';
      if(s!=='DEPARTED'&&hh%67===0) s='CANCELLED';
    }

    fl.push({
      al:al.padEnd(W_AL).substring(0,W_AL),
      fn:fn.substring(0,W_FN),
      ds:dt[0].substring(0,W_DS).padEnd(W_DS),
      tm:p2(hour)+':'+p2(min),
      gt:(gx+gn).substring(0,W_GT).padEnd(W_GT),
      st:s.padEnd(W_ST).substring(0,W_ST),
      sr:s.trim(),
      _t:rt
    });

    /* Variable interval: peak hours = denser flights */
    const isPeak=(hour>=6&&hour<=9)||(hour>=16&&hour<=19);
    const isNight=hour>=23||hour<5;
    const base=isPeak?3:isNight?8:5;
    t+=base+(fnHash(i*3+5,ap.sd+7)%(base+2));
    if(!linear&&t>=1440)t-=1440;
  }
  return fl;
}

const EMPTY={al:'  ',fn:'    ',ds:'              ',tm:'     ',gt:'    ',st:'         ',sr:''};

/* ═══ AIRPORT COORDINATES (lat, lon) for geo-nearest ═══ */
const AP_GEO={
FRA:[50.03,8.57],LHR:[51.47,-0.46],AMS:[52.31,4.76],CDG:[49.01,2.55],FCO:[41.80,12.25],
IST:[41.28,28.73],MUC:[48.35,11.79],ZRH:[47.46,8.55],MAD:[40.47,-3.57],BCN:[41.30,2.08],
LIS:[38.77,-9.13],VIE:[48.11,16.57],BRU:[50.90,4.48],CPH:[55.62,12.66],OSL:[60.19,11.10],
ARN:[59.65,17.92],HEL:[60.32,24.96],DUB:[53.42,-6.27],MAN:[53.35,-2.27],EDI:[55.95,-3.37],
WAW:[52.17,20.97],PRG:[50.10,14.26],BUD:[47.44,19.26],ATH:[37.94,23.94],
DXB:[25.25,55.36],DOH:[25.27,51.61],AUH:[24.43,54.65],JED:[21.68,39.16],
CAI:[30.12,31.41],NBO:[-1.32,36.93],JNB:[-26.13,28.23],CMN:[33.37,-7.59],
ADD:[8.98,38.80],LOS:[6.58,3.32],
HND:[35.55,139.78],NRT:[35.76,140.39],PEK:[40.08,116.58],PVG:[31.14,121.81],
CAN:[23.39,113.30],HKG:[22.31,113.91],ICN:[37.46,126.44],SIN:[1.35,103.99],
BKK:[13.69,100.75],DEL:[28.57,77.09],KUL:[2.74,101.70],CGK:[-6.13,106.66],
MNL:[14.51,121.02],TPE:[25.08,121.23],KIX:[34.43,135.24],
JFK:[40.64,-73.78],EWR:[40.69,-74.17],LAX:[33.94,-118.41],ORD:[41.97,-87.91],
ATL:[33.64,-84.43],SFO:[37.62,-122.38],MIA:[25.80,-80.29],DFW:[32.90,-97.04],
IAH:[29.99,-95.34],SEA:[47.45,-122.31],DEN:[39.86,-104.67],BOS:[42.37,-71.02],
YYZ:[43.68,-79.63],MEX:[19.44,-99.07],GRU:[-23.43,-46.47],EZE:[-34.82,-58.54],
BOG:[4.70,-74.15],SCL:[-33.39,-70.79],LIM:[-12.02,-77.11],CUN:[21.04,-86.87],
SYD:[-33.95,151.18],MEL:[-37.67,144.84],AKL:[-37.01,174.79],PER:[-31.94,115.97],
BER:[52.36,13.51],HAM:[53.63,10.01],DUS:[51.28,6.77],MXP:[45.63,8.72],
GVA:[46.24,6.11],NCE:[43.66,7.22],TLV:[32.01,34.89],
SVO:[55.97,37.41],LED:[59.80,30.26],
BOM:[19.09,72.87],BLR:[13.20,77.71],MAA:[12.99,80.17],
LAS:[36.08,-115.15],HNL:[21.32,-157.92],ANC:[61.17,-150.00],
MSP:[44.88,-93.22],DTW:[42.21,-83.35],PHL:[39.87,-75.24],CLT:[35.21,-80.94],
PHX:[33.44,-111.99],MCO:[28.43,-81.31],SAN:[32.73,-117.19],PDX:[45.59,-122.60],
BWI:[39.18,-76.67],DCA:[38.85,-77.04],IAD:[38.95,-77.46],TPA:[27.98,-82.53],
BNA:[36.13,-86.68],AUS:[30.19,-97.67],SLC:[40.79,-111.98],STL:[38.75,-90.37],
MCI:[39.30,-94.71],PIT:[40.50,-80.23],CLE:[41.41,-81.85],CVG:[39.05,-84.66],
FLL:[26.07,-80.15],MSY:[29.99,-90.26],OAK:[37.72,-122.22],SJC:[37.36,-121.93],
SMF:[38.70,-121.59],RDU:[35.88,-78.79],IND:[39.72,-86.29],CMH:[39.99,-82.89],
OKC:[35.39,-97.60],MEM:[35.04,-89.98],JAX:[30.49,-81.69],SAT:[29.53,-98.47],
RNO:[39.50,-119.77],TUS:[32.12,-110.94],ELP:[31.81,-106.38],ABQ:[35.04,-106.61],
BOI:[43.56,-116.22],BUF:[42.94,-78.73],HOU:[29.65,-95.28],MDW:[41.79,-87.75],
OMA:[41.30,-95.89],TUL:[36.20,-95.89],LIT:[34.73,-92.22],RIC:[37.51,-77.32],
ROC:[43.12,-77.67],SYR:[43.11,-76.11],FAT:[36.78,-119.72],GEG:[47.62,-117.53],
GDL:[20.52,-103.31],MTY:[25.78,-100.11],CUN:[21.04,-86.87],
PUJ:[18.57,-68.36],SJU:[18.44,-66.00],SDQ:[18.43,-69.67],NAS:[25.04,-77.47],
GIG:[-22.81,-43.25],BSB:[-15.87,-47.92],MDE:[6.17,-75.42],UIO:[-0.13,-78.49],
CTU:[30.58,103.95],SZX:[22.64,114.21],XIY:[34.45,108.75],
BNE:[-27.38,153.12],ADL:[-34.94,138.53],CHC:[-43.49,172.53],
YVR:[49.19,-123.18],YUL:[45.47,-73.74],YYC:[51.11,-114.02],YOW:[45.32,-75.67],
CPT:[-33.96,18.60],DAR:[-6.88,39.20],ACC:[5.61,-0.17],
AMM:[31.72,35.99],BEY:[33.82,35.49],RUH:[24.96,46.70],KWI:[29.23,47.97],
HAN:[21.22,105.81],SGN:[10.82,106.65],DPS:[-8.75,115.17],HKT:[8.11,98.32],
CMB:[7.18,79.88],DAC:[23.84,90.40],KTM:[27.70,85.36],
CTG:[10.44,-75.51],GYE:[-2.16,-79.88],MVD:[-34.84,-56.03],
};

/* Haversine — returns km */
function geoDistKm(lat1,lon1,lat2,lon2){
  const R=6371,d2r=Math.PI/180;
  const dLat=(lat2-lat1)*d2r,dLon=(lon2-lon1)*d2r;
  const a=Math.sin(dLat/2)**2+Math.cos(lat1*d2r)*Math.cos(lat2*d2r)*Math.sin(dLon/2)**2;
  return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));
}

/* Find nearest airport index from coordinates */
function findNearestAirport(lat,lon){
  let best=-1,bestD=Infinity;
  for(let i=0;i<AP.length;i++){
    const g=AP_GEO[AP[i].c];
    if(!g)continue;
    const d=geoDistKm(lat,lon,g[0],g[1]);
    if(d<bestD){bestD=d;best=i}
  }
  return best;
}

function fChars(fl){
  const c=[];
  for(let i=0;i<W_AL;i++)c.push(fl.al[i]||' ');
  for(let i=0;i<W_FN;i++)c.push(fl.fn[i]||' ');
  for(let i=0;i<W_DS;i++)c.push(fl.ds[i]||' ');
  for(let i=0;i<W_TM;i++)c.push(fl.tm[i]||' ');
  for(let i=0;i<W_GT;i++)c.push(fl.gt[i]||' ');
  for(let i=0;i<W_ST;i++)c.push(fl.st[i]||' ');
  return c;
}
